# Default values for nodejs , fastapi, mariadb.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 7

image:
  frontend:
    repository: gwakbyeongguk/prj-frontend
    tag: "20241108.1"

  mariadb:
    repository: mariadb:10.6.19-focal
    tag: "latest"

  admin:
    repository: gwakbyeongguk/prj-admin
    tag: "20241108.1"

  visitor:
    repository: gwakbyeongguk/prj-visitor
    tag: "20241108.1"
service:
  frontend:
    repository: gwakbyeongguk/prj-frontend
    tag: "20241108.1"
    port: 3000

  mariadb:
    port: 3306

  admin:
    repository: gwakbyeongguk/prj-admin
    tag: "20241108.1"
    port: 8000

  visitor:
    repository: gwakbyeongguk/prj-visitor
    tag: "20241108.1"
    port: 8050
